# Generated by Django 6.0.3 on 2026-04-01 22:57

import accounts.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Your date of birth. Must be 13+ years for registartion', null=True, validators=[accounts.validators.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Your country code', max_length=2, null=True),
        ),
    ]
