# Generated by Django 6.0.3 on 2026-04-18 21:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_birth_date_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Your date of birth. Must be 13+ years for registartion', null=True),
        ),
    ]
