# Generated by Django 6.0.3 on 2026-04-01 19:49

import blog.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_remove_post_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(help_text='Upload your image (allowed formats: .png, .jpeg, .jpg, .webp files; max file size: 5 MB)', upload_to='images/', validators=[blog.validators.validate_image_extension, blog.validators.validate_image_file]),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'post'], name='blog_like_user_id_8abb14_idx'),
        ),
    ]
