# Generated by Django 6.0.3 on 2026-05-31 19:15

import blog.validators
import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_text'),
        ('tags', '0002_alter_tag_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order priority (ascending)', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Your category title', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative image text', max_length=100, null=True, verbose_name='Alternative text'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(help_text='Upload your image (allowed formats: .png, .jpeg, .jpg, .webp files; max file size: 5 MB)', upload_to='images/', validators=[blog.validators.validate_image_extension, blog.validators.validate_image_file], verbose_name='Image file'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(help_text='This image belongs to (post)', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(help_text='Post that was liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(help_text='User, who liked the post', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Post category (optional)', related_name='posts', to='blog.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='Post description (optional)', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='your post tag (optional)', related_name='posts', to='tags.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Post text', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Your post title', max_length=255, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(help_text='User, created post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
