# Generated by Django 6.0.3 on 2026-06-03 21:40

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_created_at_alter_category_slug_and_more'),
        ('tags', '0004_tag_title_en_tag_title_uk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(help_text='Your category title', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(help_text='Your category title', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.CharField(blank=True, help_text='Post description (optional)', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_uk',
            field=models.CharField(blank=True, help_text='Post description (optional)', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Post text', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Post text', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(help_text='Your post title', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uk',
            field=models.CharField(help_text='Your post title', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title_uk'], name='blog_catego_title_u_1e2ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title_en'], name='blog_catego_title_e_497f26_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title_uk'], name='blog_post_title_e1c6f7_idx-uk'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title_en'], name='blog_post_title_e1c6f7_idx-en'),
        ),
    ]
