# Generated by Django 6.0.3 on 2026-06-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_title_en_category_title_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Your category title', max_length=255, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(help_text='Your category title', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_uk',
            field=models.CharField(help_text='Your category title', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
    ]
