# Generated by Django 6.0.3 on 2026-03-17 18:24

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=255, unique=True)),
                ('title', models.CharField(help_text='Tag title', max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='tags_tag_title_fb756e_idx')],
            },
        ),
    ]
