# Generated by Django 6.0.3 on 2026-05-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='Tag title', max_length=50, verbose_name='Title'),
        ),
    ]
