# Generated by Django 6.0.3 on 2026-06-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_created_at_alter_tag_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(help_text='Tag title', max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_uk',
            field=models.CharField(help_text='Tag title', max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title_uk'], name='tags_tag_title_fb756e_idx-uk'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title_en'], name='tags_tag_title_fb756e_idx-en'),
        ),
    ]
