# Generated by Django 6.0.3 on 2026-06-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_tag_title_en_tag_title_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='Tag title', max_length=50, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_en',
            field=models.CharField(help_text='Tag title', max_length=50, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_uk',
            field=models.CharField(help_text='Tag title', max_length=50, null=True, unique=True, verbose_name='Title'),
        ),
    ]
