# Security settings with nh3

# settings for bio field in accounts/models.py
NH3_BIO_SETTINGS = {
    "tags": {
        "b",
        "i",
        "em",
        "strong",
        "p",
        "br",
        "a",
        "ul",
        "li",
        "ol",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "blockquote",
        "u",
        "s",
        "span",
        "div",
    },
    "attributes": {
        "a": {
            "href",
            "title",
            "target",
        },
        "span": {"style", "class"},
        "p": {"style", "class"},
        "div": {"style", "class"},
        "h2": {"style", "class"},
        "h3": {"style", "class"},
        "h4": {"style", "class"},
        "h5": {"style", "class"},
        "h6": {"style", "class"},
        "ul": {"style", "class"},
        "ol": {"style", "class"},
        "li": {"style", "class"},
    },
}
# settings for post's text field in blog/models.py
NH3_POST_SETTINGS = {
    "tags": {
        "b",
        "i",
        "em",
        "strong",
        "p",
        "br",
        "a",
        "ul",
        "li",
        "ol",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "blockquote",
        "img",
        "u",
        "s",
        "pre",
        "code",
        "span",
        "div",
        "hr",
    },
    "attributes": {
        "a": {
            "href",
            "title",
            "target",
        },
        "img": {"src", "alt", "width", "height", "style", "class", "style"},
        "*": {
            "class",
        },
        "code": {
            "class",
        },
        "pre": {
            "class",
        },
        "span": {"style", "class"},
        "p": {"style", "class"},
        "div": {"style", "class"},
        "h2": {"style", "class"},
        "h3": {"style", "class"},
        "h4": {"style", "class"},
        "h5": {"style", "class"},
        "h6": {"style", "class"},
        "ul": {"style", "class"},
        "ol": {"style", "class"},
        "li": {"style", "class"},
    },
}
